# Ansible Inventory Template
# This file is generated by Terraform and lists all servers for Ansible to manage

all:
  children:
    webservers:
      hosts:
        web-server-1:
          ansible_host: ${web_server_1_ip}
          ansible_user: ubuntu
          server_role: primary
        web-server-2:
          ansible_host: ${web_server_2_ip}
          ansible_user: ubuntu
          server_role: secondary
      vars:
        ansible_ssh_private_key_file: ansible-key.pem
        ansible_python_interpreter: /usr/bin/python3

# 🎓 Inventory Structure Explained:
# 
# all: Root group containing all servers
# └── webservers: Group for web server instances
#     ├── web-server-1: Individual server with specific IP
#     └── web-server-2: Individual server with specific IP
#
# vars: Variables applied to the entire webservers group
# - SSH key file for authentication
# - Python interpreter path for Ansible modules
#
# 💡 Why This Structure:
# - Groups allow targeting specific server types
# - Variables avoid repetition in each host
# - Role tags help identify server purposes
# - Clear naming makes management easier